FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# galaxygearapp

Simple API to return items of gear for Rebel Fighters and Stormtroopers

## Products Collection [/products.json]

### List All Questions [GET]

+ Response 200 (application/json)

        {
           "data":[
              {
                 "id":"3",
                 "type":"products",
                 "attributes":{
                    "name":"LoneTrooper Tent",
                    "description":"Ideal for Troopers going off on lone suicidal missions. Automatically returns to us when you die. The Empire must recycle!",
                    "is-shared":false,
                    "shared-capacity":0,
                    "weight-value":"1000.0",
                    "weight-unit":"g"
                 },
                 "relationships":{
                    "manufacturer":{
                       "data":{
                          "id":"1",
                          "type":"manufacturers"
                       }
                    },
                    "category":{
                       "data":{
                          "id":"2",
                          "type":"categories"
                       }
                    },
                    "product-assets":{
                       "data":[
        
                       ]
                    }
                 }
              },
              {
                 "id":"4",
                 "type":"products",
                 "attributes":{
                    "name":"Squad Tent",
                    "description":"Perfect for that cosy squad feeling after a hard day killing Rebel Scum",
                    "is-shared":true,
                    "shared-capacity":4,
                    "weight-value":"2000.0",
                    "weight-unit":"g"
                 },
                 "relationships":{
                    "manufacturer":{
                       "data":{
                          "id":"1",
                          "type":"manufacturers"
                       }
                    },
                    "category":{
                       "data":{
                          "id":"2",
                          "type":"categories"
                       }
                    },
                    "product-assets":{
                       "data":[
        
                       ]
                    }
                 }
              }
           ]
        }

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }