FORMAT: 1A
HOST: http://galaxygearapp.herokuapp.com/

# galaxygearapp

Simple API to return items of gear (called Products in the API) for Rebel Fighters and Stormtroopers.
It follows the JSONAPI standard, with 'data' as the root notde of each object. Related objects are contained
in 'relationships' object nodes.

## Products Collection [/products.json]

### List All Products [GET]

Returns all products and their related objects (if they exist).

Paging is not currently supported.

#### Required:

    None.

#### Relationship objects:

    None (returned in response body).


+ Response 200 (application/json)

    + Body
        
            {
               "data":[
                  {
                     "id":"3",
                     "type":"products",
                     "attributes":{
                        "name":"LoneTrooper Tent",
                        "description":"Ideal for Troopers going off on lone suicidal missions. Automatically returns to us when you die. The Empire must recycle!",
                        "is-shared":false,
                        "shared-capacity":0,
                        "weight-value":"1000.0",
                        "weight-unit":"g"
                     },
                     "relationships":{
                        "manufacturer":{
                           "data":{
                              "id":"1",
                              "type":"manufacturers"
                           }
                        },
                        "category":{
                           "data":{
                              "id":"2",
                              "type":"categories"
                           }
                        },
                        "product-assets":{
                           "data":[
            
                           ]
                        }
                     }
                  },
                  {
                     "id":"4",
                     "type":"products",
                     "attributes":{
                        "name":"Squad Tent",
                        "description":"Perfect for that cosy squad feeling after a hard day killing Rebel Scum",
                        "is-shared":true,
                        "shared-capacity":4,
                        "weight-value":"2000.0",
                        "weight-unit":"g"
                     },
                     "relationships":{
                        "manufacturer":{
                           "data":{
                              "id":"1",
                              "type":"manufacturers"
                           }
                        },
                        "category":{
                           "data":{
                              "id":"2",
                              "type":"categories"
                           }
                        },
                        "product-assets":{
                           "data":[
            
                           ]
                        }
                     }
                  }
               ]
            }

## Product [/products/{product_id}.json]

### View a Product [GET]



+ Response 200 (application/json)

    + Body

### Create a New Product [POST]

Accepts a single object containing a product and two relationship objects.

#### Required:

    String: name (cannot be blank/null/empty)

#### Relationship objects:

    Category (required): the category id
    Manufacturer (optional): the manufacturer id. Can be null it not needed, eg:
    
    "manufacturer":{
        "data":null
        }
     }

+ Request (application/json)

    + Body
    
            {
               "data":{
                  "attributes":{
                     "name":"test",
                     "description":null,
                     "weight-value":null,
                     "weight-unit":null,
                     "is-shared":false,
                     "shared-capacity":null
                  },
                  "relationships":{
                     "category":{
                        "data":{
                           "type":"categories",
                           "id":"7"
                        }
                     },
                     "manufacturer":{
                        "data":{
                           "type":"manufacturers",
                           "id":"1"
                        }
                     }
                  },
                  "type":"products"
               }
            }

+ Response 201 (application/json)

    + Body
    
            {
               "data":{
                  "id":"20",
                  "type":"products",
                  "attributes":{
                     "name":"test",
                     "description":null,
                     "is-shared":false,
                     "shared-capacity":null,
                     "weight-value":null,
                     "weight-unit":null
                  },
                  "relationships":{
                     "manufacturer":{
                        "data":{
                           "id":"1",
                           "type":"manufacturers"
                        }
                     },
                     "category":{
                        "data":{
                           "id":"7",
                           "type":"categories"
                        }
                     },
                     "product-assets":{
                        "data":[
                        ]
                     }
                  }
               }
            }
            

### Delete a New Product [DELETE]

Supply the ID of the product to delete at the end of the url. No body required.

#### Required fields:

    ProductID: at the end of the url

#### Relationship objects:

    None
    
+ Request (application/json)

+ Response 204