# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

cat1 = Category.create(name: 'Carrying system')
cat2 = Category.create(name: 'Shelter system')
cat3 = Category.create(name: 'Sleep system')
cat4 = Category.create(name: 'Cooking system')
cat5 = Category.create(name: 'Hydration system')
cat6 = Category.create(name: 'Consumable') 
cat7 = Category.create(name: 'Navigation Equipment')
cat8 = Category.create(name: 'Electronics')
cat9 = Category.create(name: 'Worn')
cat10 = Category.create(name: 'Fun Extras')
cat11 = Category.create(name: 'Fishing Equipment')	    
cat12 = Category.create(name: 'Hunting Equipment')
cat13 = Category.create(name: 'Photography Equipment')
cat14 = Category.create(name: 'Emergency/Repair Equipment')
cat15 = Category.create(name: 'Other')

man1 = Manufacturer.create(name:'Vader Outfitters Unlimited')
man2 = Manufacturer.create(name:'Rebel Supplies Corp')

prod1 = Product.create(name:'Backpack', category: cat1, weight_value: 500, weight_unit: 'g')
prod2 = Product.create(name:'Munitions Belt', category: cat1, manufacturer: man1, description: 'Easy access to the ammo you need.', weight_value: 150, weight_unit: 'g')
prod3 = Product.create(name:'LoneTrooper Tent', category: cat2, manufacturer: man1, description: 'Ideal for Troopers going off on lone suicidal missions. Automatically returns to us when you die. The Empire must recycle!', weight_value: 1000, weight_unit: 'g')
prod4 = Product.create(name:'Squad Tent', category: cat2, manufacturer: man1, is_shared: true, shared_capacity: 4, description: 'Perfect for that cosy squad feeling after a hard day killing Rebel Scum', weight_value: 2000, weight_unit: 'g')
prod5 = Product.create(name:'Platoon Tent', category: cat2, manufacturer: man1, is_shared: true, shared_capacity: 20, description: 'Built in forcefiled protection for your entire platoon!', weight_value: 10000, weight_unit: 'g')
prod6 = Product.create(name:'Double sleeping bag', category: cat3, manufacturer: man1, weight_value: 50, weight_unit: 'g')
prod7 = Product.create(name:'Portable stove', category: cat4, manufacturer: man1, weight_value: 25, weight_unit: 'g')
prod8 = Product.create(name:'Water bottle', category: cat5, manufacturer: man1, weight_value: 2, weight_unit: 'g')
prod9 = Product.create(name:'Ration pack (1 day)', category: cat6, manufacturer: man1, weight_value: 25, weight_unit: 'g')
prod10 = Product.create(name:'GPS brain implant', category: cat7, manufacturer: man1, weight_value: 0.01, weight_unit: 'g')
prod11 = Product.create(name:'Walkie talkie', category: cat8, manufacturer: man1, weight_value: 3.5, weight_unit: 'g')
prod12 = Product.create(name:'IR Heat tracking radar goggles', category: cat9, manufacturer: man1, weight_value: 150, weight_unit: 'g')
prod13 = Product.create(name:'Stun rod', category: cat10, manufacturer: man1, weight_value: 6.75, weight_unit: 'g')
prod14 = Product.create(name:'Stun grenade (detonates underwater)', category: cat11, manufacturer: man1, weight_value: 4, weight_unit: 'g')
prod15 = Product.create(name:'Rebel Tracking drone', category: cat12, manufacturer: man1, weight_value: 4.25, weight_unit: 'g')
prod16 = Product.create(name:'Flash gun', category: cat13, manufacturer: man1, weight_value: 1.25, weight_unit: 'g')
prod17 = Product.create(name:'Repair Droid', category: cat14, manufacturer: man1, weight_value: 8500, weight_unit: 'g')
prod18 = Product.create(name:'Hover bike', category: cat15, manufacturer: man1, weight_value: 50000, weight_unit: 'g')
